import { WorkforceData } from './types';

export const generateMockWorkforceData = (): WorkforceData => ({
  kpis: {
    totalFTE: 847,
    plannedFTE: 892,
    staffingCoverage: 94.2,
    openPositionsCritical: 12,
    sickLeaveRate: 6.8,
  },
  departments: [
    {
      id: '1',
      name: 'Emergency Medicine',
      riskLevel: 'high',
      vacancyRate: 18,
      sickLeaveTrend: 'up',
      overtimeHours: 245,
      contractExpiries: 3,
    },
    {
      id: '2',
      name: 'Internal Medicine',
      riskLevel: 'medium',
      vacancyRate: 12,
      sickLeaveTrend: 'stable',
      overtimeHours: 156,
      contractExpiries: 2,
    },
    {
      id: '3',
      name: 'Surgery',
      riskLevel: 'stable',
      vacancyRate: 5,
      sickLeaveTrend: 'down',
      overtimeHours: 89,
      contractExpiries: 0,
    },
    {
      id: '4',
      name: 'Pediatrics',
      riskLevel: 'medium',
      vacancyRate: 10,
      sickLeaveTrend: 'up',
      overtimeHours: 134,
      contractExpiries: 1,
    },
    {
      id: '5',
      name: 'Radiology',
      riskLevel: 'stable',
      vacancyRate: 3,
      sickLeaveTrend: 'stable',
      overtimeHours: 42,
      contractExpiries: 0,
    },
    {
      id: '6',
      name: 'Cardiology',
      riskLevel: 'stable',
      vacancyRate: 6,
      sickLeaveTrend: 'down',
      overtimeHours: 67,
      contractExpiries: 1,
    },
  ],
  costs: {
    monthlyPersonnelCost: 4250000,
    monthlyBudget: 4500000,
    overtimeCost: 185000,
    overtimeTrend: 'up',
    insight: 'Emergency Medicine agency spend ↑18% MoM due to 2 vacancies',
  },
  hiringBlockers: [
    {
      id: '1',
      role: 'Senior Cardiologist',
      daysOpen: 67,
      blockerType: 'candidate_pipeline',
      isCritical: true,
    },
    {
      id: '2',
      role: 'ICU Nurse (x3)',
      daysOpen: 45,
      blockerType: 'approval_delay',
      isCritical: true,
    },
    {
      id: '3',
      role: 'Anesthesiologist',
      daysOpen: 34,
      blockerType: 'onboarding_admin',
      isCritical: true,
    },
  ],
  internationalHires: [
    {
      id: '1',
      name: 'Dr. Ana García',
      status: 'in_progress',
      country: 'Spain',
    },
    {
      id: '2',
      name: 'Dr. Pavel Novak',
      status: 'pending',
      country: 'Czech Republic',
    },
    {
      id: '3',
      name: 'Dr. Maria Santos',
      status: 'approved',
      country: 'Brazil',
    },
  ],
  lastUpdated: new Date(),
  isDemo: true,
});
