INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'EU Blue Card für Ärzte in Deutschland 2026: Voraussetzungen & Ablauf', 'blaue-karte-eu-aerzte-deutschland-2026', 'Alles, was Ärzte über die Blaue Karte EU in Deutschland wissen müssen. Gehaltsanforderungen, Antragsprozess, Vorteile und Weg zur Niederlassungserlaubnis.', content, 'https://images.unsplash.com/photo-1523287562758-66c7fc58967f?w=1200&h=630&fit=crop', 'visa', '8 min read', 'de', 'Blaue Karte EU für Ärzte in Deutschland 2026 | Voraussetzungen & Vorteile', 'Kompletter Leitfaden zur Blauen Karte EU für Ärzte in Deutschland. Gehaltsschwellen, Antragsprozess, Niederlassungserlaubnis und Familiennachzug.', 'Blue Card, Blaue Karte EU, Arbeitsvisum, Ärzte Deutschland', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'blue-card-doctors-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Tarjeta Azul UE para Médicos en Alemania 2026: Requisitos y Proceso', 'tarjeta-azul-ue-medicos-alemania-2026', 'Todo lo que los médicos necesitan saber sobre la Tarjeta Azul UE en Alemania.', content, 'https://images.unsplash.com/photo-1523287562758-66c7fc58967f?w=1200&h=630&fit=crop', 'visa', '8 min read', 'es', 'Tarjeta Azul UE para Médicos en Alemania 2026 | Requisitos y Beneficios', 'Guía completa de la Tarjeta Azul UE para médicos en Alemania. Umbrales salariales, proceso de solicitud, residencia permanente.', 'tarjeta azul, EU Blue Card, visa trabajo, médicos alemania', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'blue-card-doctors-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Carte Bleue UE pour Médecins en Allemagne 2026 : Conditions et Procédure', 'carte-bleue-ue-medecins-allemagne-2026', 'Tout ce que les médecins doivent savoir sur la Carte Bleue UE en Allemagne.', content, 'https://images.unsplash.com/photo-1523287562758-66c7fc58967f?w=1200&h=630&fit=crop', 'visa', '8 min read', 'fr', 'Carte Bleue UE pour Médecins en Allemagne 2026 | Conditions et Avantages', 'Guide complet de la Carte Bleue UE pour les médecins en Allemagne. Seuils de salaire, procédure, résidence permanente.', 'carte bleue, EU Blue Card, visa travail, médecins allemagne', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'blue-card-doctors-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Голубая карта ЕС для врачей в Германии 2026: Требования и процесс', 'golubaja-karta-es-vrachi-germanija-2026', 'Всё, что врачам нужно знать о Голубой карте ЕС в Германии.', content, 'https://images.unsplash.com/photo-1523287562758-66c7fc58967f?w=1200&h=630&fit=crop', 'visa', '8 min read', 'ru', 'Голубая карта ЕС для врачей в Германии 2026 | Требования и преимущества', 'Полное руководство по Голубой карте ЕС для врачей в Германии. Зарплатные пороги, процесс подачи, ПМЖ.', 'голубая карта, EU Blue Card, рабочая виза, врачи германия', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'blue-card-doctors-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Arztgehalt in Deutschland 2026: Nach Fachrichtung, Erfahrung & Region', 'arztgehalt-deutschland-2026-nach-fachrichtung', 'Umfassende Aufschlüsselung der Arztgehälter in Deutschland 2026.', content, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&h=630&fit=crop', 'salaries', '10 min read', 'de', 'Arztgehalt Deutschland 2026 | Nach Fachrichtung & Erfahrung', 'Vollständige Aufschlüsselung der Arztgehälter in Deutschland 2026. Assistenzarzt bis Chefarzt.', 'Arztgehalt, Deutschland, Assistenzarzt, Facharzt, Oberarzt', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'doctor-salary-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Salario Médico en Alemania 2026: Por Especialidad, Experiencia y Región', 'salario-medico-alemania-2026-por-especialidad', 'Desglose completo de los salarios médicos en Alemania 2026.', content, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&h=630&fit=crop', 'salaries', '10 min read', 'es', 'Salario Médico en Alemania 2026 | Por Especialidad y Experiencia', 'Desglose completo de salarios médicos en Alemania 2026. De residente a jefe de servicio.', 'salario médico, alemania, Arztgehalt, Facharzt, Oberarzt', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'doctor-salary-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Salaire Médecin en Allemagne 2026 : Par Spécialité, Expérience et Région', 'salaire-medecin-allemagne-2026-par-specialite', 'Analyse complète des salaires médicaux en Allemagne 2026.', content, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&h=630&fit=crop', 'salaries', '10 min read', 'fr', 'Salaire Médecin Allemagne 2026 | Par Spécialité et Expérience', 'Analyse complète des salaires médicaux en Allemagne 2026. Du résident au chef de service.', 'salaire médecin, allemagne, Arztgehalt, Facharzt, Oberarzt', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'doctor-salary-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Зарплата врача в Германии 2026: По специальности, опыту и региону', 'zarplata-vracha-germanija-2026-po-specialnosti', 'Полный разбор зарплат врачей в Германии 2026.', content, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&h=630&fit=crop', 'salaries', '10 min read', 'ru', 'Зарплата врача Германия 2026 | По специальности и опыту', 'Полный разбор зарплат врачей в Германии 2026. От ассистента до главврача.', 'зарплата врача, германия, Arztgehalt, Facharzt, Oberarzt', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'doctor-salary-germany-2026' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Unterlagen für die Approbation in Deutschland: Vollständige Checkliste 2026', 'unterlagen-approbation-deutschland-checkliste-2026', 'Vollständige Checkliste aller Dokumente für den Approbationsantrag in Deutschland.', content, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'de', 'Unterlagen Approbation Deutschland 2026 | Vollständige Checkliste', 'Vollständige Checkliste der Unterlagen für die Approbation in Deutschland 2026.', 'Unterlagen Approbation, Checkliste, Apostille, vereidigter Übersetzer', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'documents-needed-approbation-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Documentos Necesarios para la Approbation en Alemania: Lista Completa 2026', 'documentos-necesarios-approbation-alemania-2026', 'Lista completa de documentos requeridos para la solicitud de Approbation en Alemania.', content, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'es', 'Documentos para Approbation Alemania 2026 | Lista Completa', 'Lista completa de documentos necesarios para la Approbation en Alemania 2026.', 'documentos approbation, lista, apostilla, traductor jurado', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'documents-needed-approbation-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Documents Nécessaires pour l''Approbation en Allemagne : Liste Complète 2026', 'documents-necessaires-approbation-allemagne-2026', 'Liste complète de tous les documents requis pour la demande d''Approbation en Allemagne.', content, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'fr', 'Documents Approbation Allemagne 2026 | Liste Complète', 'Liste complète des documents nécessaires pour l''Approbation en Allemagne 2026.', 'documents approbation, liste, apostille, traducteur assermenté', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'documents-needed-approbation-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Документы для апробации в Германии: Полный чек-лист 2026', 'dokumenty-dlya-approbacii-germaniya-2026', 'Полный чек-лист всех документов для подачи на апробацию в Германии.', content, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'ru', 'Документы для апробации Германия 2026 | Полный чек-лист', 'Полный чек-лист документов для апробации в Германии 2026.', 'документы апробация, чек-лист, апостиль, присяжный переводчик', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'documents-needed-approbation-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Fachsprachprüfung (FSP) Vorbereitung: Leitfaden zum Bestehen', 'fachsprachpruefung-fsp-vorbereitung-leitfaden-2026', 'Meistern Sie die Fachsprachprüfung mit diesem umfassenden Vorbereitungsleitfaden.', content, 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=630&fit=crop', 'language-learning', '11 min read', 'de', 'FSP Prüfungsvorbereitung 2026 | Fachsprachprüfung Tipps', 'Wie Sie die Fachsprachprüfung (FSP) bestehen. Prüfungsaufbau, Lerntipps, Anamnese-Übungen.', 'FSP, Fachsprachprüfung, medizinisches Deutsch, Anamnese, Arztbrief', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'fachsprachpruefung-fsp-preparation-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Fachsprachprüfung (FSP): Guía de Preparación para el Examen de Alemán Médico', 'fachsprachpruefung-fsp-guia-preparacion-2026', 'Domine la Fachsprachprüfung con esta guía completa de preparación.', content, 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=630&fit=crop', 'language-learning', '11 min read', 'es', 'Guía Preparación FSP 2026 | Fachsprachprüfung Consejos', 'Cómo aprobar la Fachsprachprüfung (FSP). Estructura del examen, consejos, práctica de Anamnese.', 'FSP, Fachsprachprüfung, alemán médico, examen idioma, Anamnese', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'fachsprachpruefung-fsp-preparation-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Fachsprachprüfung (FSP) : Guide de Préparation à l''Examen d''Allemand Médical', 'fachsprachpruefung-fsp-guide-preparation-2026', 'Maîtrisez la Fachsprachprüfung avec ce guide de préparation complet.', content, 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=630&fit=crop', 'language-learning', '11 min read', 'fr', 'Guide Préparation FSP 2026 | Fachsprachprüfung Conseils', 'Comment réussir la Fachsprachprüfung (FSP). Structure de l''examen, conseils, pratique Anamnese.', 'FSP, Fachsprachprüfung, allemand médical, examen langue, Anamnese', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'fachsprachpruefung-fsp-preparation-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Fachsprachprüfung (FSP): Руководство по подготовке к экзамену', 'fachsprachpruefung-fsp-podgotovka-rukovodstvo-2026', 'Освойте Fachsprachprüfung с этим полным руководством по подготовке.', content, 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=630&fit=crop', 'language-learning', '11 min read', 'ru', 'Руководство подготовки FSP 2026 | Fachsprachprüfung Советы', 'Как сдать Fachsprachprüfung (FSP). Структура экзамена, советы по подготовке.', 'FSP, Fachsprachprüfung, медицинский немецкий, языковой экзамен', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'fachsprachpruefung-fsp-preparation-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Deutschland vs. Spanien vs. Österreich für Ärzte: Gehalt, Prozess & Lifestyle', 'deutschland-vs-spanien-vs-oesterreich-aerzte-2026', 'Detaillierter Vergleich der Arbeit als Arzt in Deutschland, Spanien und Österreich.', content, 'https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=1200&h=630&fit=crop', 'career', '11 min read', 'de', 'Deutschland vs Spanien vs Österreich für Ärzte 2026 | Kompletter Vergleich', 'Detaillierter Vergleich: Arzt in Deutschland, Spanien und Österreich. Gehälter, Anerkennung, Lebensqualität 2026.', 'Deutschland vs Spanien, Arztvergleich, Österreich, Gehaltsvergleich', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'germany-vs-spain-vs-austria-doctors' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Alemania vs España vs Austria para Médicos: Salario, Proceso y Estilo de Vida', 'alemania-vs-espana-vs-austria-medicos-2026', 'Comparación detallada de trabajar como médico en Alemania, España y Austria.', content, 'https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=1200&h=630&fit=crop', 'career', '11 min read', 'es', 'Alemania vs España vs Austria para Médicos 2026 | Comparación Completa', 'Comparación detallada: médico en Alemania, España y Austria. Salarios, reconocimiento, calidad de vida 2026.', 'alemania vs españa, comparación médicos, austria, salarios', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'germany-vs-spain-vs-austria-doctors' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Allemagne vs Espagne vs Autriche pour les Médecins : Salaire, Processus et Mode de Vie', 'allemagne-vs-espagne-vs-autriche-medecins-2026', 'Comparaison détaillée du travail de médecin en Allemagne, Espagne et Autriche.', content, 'https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=1200&h=630&fit=crop', 'career', '11 min read', 'fr', 'Allemagne vs Espagne vs Autriche Médecins 2026 | Comparaison Complète', 'Comparaison détaillée: médecin en Allemagne, Espagne et Autriche. Salaires, reconnaissance, qualité de vie 2026.', 'allemagne vs espagne, comparaison médecins, autriche, salaires', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'germany-vs-spain-vs-austria-doctors' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Германия vs Испания vs Австрия для врачей: Зарплата, процесс и образ жизни', 'germanija-vs-ispanija-vs-avstrija-vrachi-2026', 'Детальное сравнение работы врачом в Германии, Испании и Австрии.', content, 'https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=1200&h=630&fit=crop', 'career', '11 min read', 'ru', 'Германия vs Испания vs Австрия для врачей 2026 | Полное сравнение', 'Детальное сравнение: врач в Германии, Испании и Австрии. Зарплаты, признание, качество жизни 2026.', 'германия vs испания, сравнение врачей, австрия, зарплаты', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'germany-vs-spain-vs-austria-doctors' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Leben als ausländischer Arzt in Deutschland: Was Sie 2026 erwartet', 'leben-als-auslaendischer-arzt-deutschland-2026', 'Ein ehrlicher Blick auf den Alltag als internationaler Arzt in Deutschland.', content, 'https://images.unsplash.com/photo-1516841273335-e39b37888115?w=1200&h=630&fit=crop', 'life-abroad', '11 min read', 'de', 'Leben als ausländischer Arzt in Deutschland 2026 | Was Sie erwartet', 'Ehrlicher Leitfaden zum Alltag als internationaler Arzt in Deutschland. Klinikkultur, Integration, Wohnkosten 2026.', 'ausländischer Arzt Deutschland, Expat Arzt, Integration, Klinikkultur', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'life-as-foreign-doctor-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Vida como Médico Extranjero en Alemania: Qué Esperar en 2026', 'vida-como-medico-extranjero-alemania-2026', 'Una mirada honesta a la vida diaria como médico internacional en Alemania.', content, 'https://images.unsplash.com/photo-1516841273335-e39b37888115?w=1200&h=630&fit=crop', 'life-abroad', '11 min read', 'es', 'Vida como Médico Extranjero en Alemania 2026 | Qué Esperar', 'Guía honesta sobre la vida diaria como médico internacional en Alemania. Cultura hospitalaria, integración 2026.', 'médico extranjero alemania, expat médico, integración, cultura hospitalaria', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'life-as-foreign-doctor-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Vie de Médecin Étranger en Allemagne : Ce Qui Vous Attend en 2026', 'vie-medecin-etranger-allemagne-2026', 'Un regard honnête sur le quotidien de médecin international en Allemagne.', content, 'https://images.unsplash.com/photo-1516841273335-e39b37888115?w=1200&h=630&fit=crop', 'life-abroad', '11 min read', 'fr', 'Vie de Médecin Étranger en Allemagne 2026 | Ce Qui Vous Attend', 'Guide honnête sur le quotidien de médecin international en Allemagne. Culture hospitalière, intégration 2026.', 'médecin étranger allemagne, expat médecin, intégration, culture hospitalière', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'life-as-foreign-doctor-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Жизнь иностранного врача в Германии: Чего ожидать в 2026', 'zhizn-inostrannogo-vracha-germanija-2026', 'Честный взгляд на повседневную жизнь международного врача в Германии.', content, 'https://images.unsplash.com/photo-1516841273335-e39b37888115?w=1200&h=630&fit=crop', 'life-abroad', '11 min read', 'ru', 'Жизнь иностранного врача в Германии 2026 | Чего ожидать', 'Честное руководство по повседневной жизни международного врача в Германии. Больничная культура, интеграция 2026.', 'иностранный врач германия, экспат врач, интеграция, больничная культура', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'life-as-foreign-doctor-germany' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Nostrifizierung in Österreich: Leitfaden zur ärztlichen Zulassung 2026', 'nostrifizierung-oesterreich-aerztliche-zulassung-2026', 'Vollständiger Leitfaden zur Nostrifizierung in Österreich.', content, 'https://images.unsplash.com/photo-1609902726285-00668009f004?w=1200&h=630&fit=crop', 'homologation', '10 min read', 'de', 'Nostrifizierung Österreich 2026 | Leitfaden ärztliche Zulassung', 'Vollständiger Leitfaden zur Nostrifizierung in Österreich. Anerkennung, Prüfungen, Kosten und Gehälter 2026.', 'Nostrifizierung, Österreich, ärztliche Zulassung, Ärztekammer, ius practicandi', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'nostrifizierung-austria-medical-license' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Nostrifizierung en Austria: Guía de Reconocimiento de Licencia Médica 2026', 'nostrifizierung-austria-licencia-medica-2026', 'Guía completa de Nostrifizierung en Austria.', content, 'https://images.unsplash.com/photo-1609902726285-00668009f004?w=1200&h=630&fit=crop', 'homologation', '10 min read', 'es', 'Nostrifizierung Austria 2026 | Guía Reconocimiento Licencia Médica', 'Guía completa de Nostrifizierung en Austria. Reconocimiento, exámenes, costos y salarios 2026.', 'nostrifizierung, austria, licencia médica, Ärztekammer, ius practicandi', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'nostrifizierung-austria-medical-license' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Nostrifizierung en Autriche : Guide de Reconnaissance de Licence Médicale 2026', 'nostrifizierung-autriche-licence-medicale-2026', 'Guide complet de Nostrifizierung en Autriche.', content, 'https://images.unsplash.com/photo-1609902726285-00668009f004?w=1200&h=630&fit=crop', 'homologation', '10 min read', 'fr', 'Nostrifizierung Autriche 2026 | Guide Reconnaissance Licence Médicale', 'Guide complet de Nostrifizierung en Autriche. Reconnaissance, examens, coûts et salaires 2026.', 'nostrifizierung, autriche, licence médicale, Ärztekammer, ius practicandi', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'nostrifizierung-austria-medical-license' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Нострификация в Австрии: Руководство по признанию медицинской лицензии 2026', 'nostrifikacija-avstrija-medicinskaja-licenzija-2026', 'Полное руководство по нострификации в Австрии.', content, 'https://images.unsplash.com/photo-1609902726285-00668009f004?w=1200&h=630&fit=crop', 'homologation', '10 min read', 'ru', 'Нострификация Австрия 2026 | Руководство признание медицинской лицензии', 'Полное руководство по нострификации в Австрии. Признание, экзамены, стоимость и зарплаты 2026.', 'нострификация, австрия, медицинская лицензия, Ärztekammer, ius practicandi', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'nostrifizierung-austria-medical-license' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Anerkennung der ärztlichen Approbation in Deutschland: Kompletter Leitfaden 2026', 'anerkennung-aerztliche-approbation-deutschland-leitfaden-2026', 'Alles über die Anerkennung der ärztlichen Zulassung in Deutschland 2026.', content, 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&h=630&fit=crop', 'homologation', '12 min read', 'de', 'Ärztliche Approbation Deutschland 2026 | Vollständiger Leitfaden', 'Schritt-für-Schritt-Anleitung zur Anerkennung der ärztlichen Zulassung (Approbation) in Deutschland 2026.', 'Approbation, Deutschland, ärztliche Zulassung, Kenntnisprüfung, FSP', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-germany-complete-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Reconocimiento de Licencia Médica en Alemania: Guía Completa 2026 (Approbation)', 'reconocimiento-licencia-medica-alemania-guia-completa-2026', 'Todo sobre el reconocimiento de la licencia médica en Alemania 2026.', content, 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&h=630&fit=crop', 'homologation', '12 min read', 'es', 'Reconocimiento Licencia Médica Alemania 2026 | Guía Approbation', 'Guía paso a paso para obtener el reconocimiento de licencia médica (Approbation) en Alemania 2026.', 'approbation, alemania, licencia médica, Kenntnisprüfung, FSP', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-germany-complete-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Reconnaissance de Licence Médicale en Allemagne : Guide Complet 2026 (Approbation)', 'reconnaissance-licence-medicale-allemagne-guide-complet-2026', 'Tout sur la reconnaissance de la licence médicale en Allemagne 2026.', content, 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&h=630&fit=crop', 'homologation', '12 min read', 'fr', 'Reconnaissance Licence Médicale Allemagne 2026 | Guide Approbation', 'Guide étape par étape pour la reconnaissance de la licence médicale (Approbation) en Allemagne 2026.', 'approbation, allemagne, licence médicale, Kenntnisprüfung, FSP', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-germany-complete-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Признание медицинской лицензии в Германии: Полный гид 2026 (Апробация)', 'priznanie-medicinskoj-licenzii-germanija-polnyj-gid-2026', 'Всё о признании медицинской лицензии в Германии 2026.', content, 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&h=630&fit=crop', 'homologation', '12 min read', 'ru', 'Признание медицинской лицензии Германия 2026 | Гид по апробации', 'Пошаговое руководство по признанию медицинской лицензии (апробации) в Германии 2026.', 'апробация, германия, медицинская лицензия, Kenntnisprüfung, FSP', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-germany-complete-guide' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Anerkennung der ärztlichen Zulassung in Spanien: Homologación-Leitfaden 2026', 'anerkennung-aerztliche-zulassung-spanien-homologacion-2026', 'Vollständiger Leitfaden zur Homologierung Ihres Medizinstudiums in Spanien 2026.', content, 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'de', 'Anerkennung Ärztliche Zulassung Spanien 2026 | Homologación-Leitfaden', 'Vollständiger Leitfaden zur Homologierung in Spanien. Prozess, Dokumente, Kosten und Zeitrahmen 2026.', 'Homologación, Spanien, ärztliche Zulassung, MEFP, Colegio de Médicos', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-spain-homologacion' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Homologación del Título Médico en España: Guía Completa 2026', 'homologacion-titulo-medico-espana-guia-2026', 'Guía completa para homologar tu título médico en España 2026.', content, 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'es', 'Homologación Título Médico España 2026 | Guía Completa', 'Guía completa para homologar tu título médico en España. Proceso, documentos, costos y plazos 2026.', 'homologación, españa, título médico, MEFP, Colegio de Médicos', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-spain-homologacion' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Reconnaissance de Licence Médicale en Espagne : Guide Homologación 2026', 'reconnaissance-licence-medicale-espagne-homologacion-2026', 'Guide complet pour faire reconnaître votre diplôme médical en Espagne 2026.', content, 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'fr', 'Reconnaissance Licence Médicale Espagne 2026 | Guide Homologación', 'Guide complet pour faire reconnaître votre diplôme médical en Espagne. Processus, documents, coûts et délais 2026.', 'homologación, espagne, licence médicale, MEFP, Colegio de Médicos', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-spain-homologacion' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Признание медицинской лицензии в Испании: Руководство по гомологации 2026', 'priznanie-medicinskoj-licenzii-ispanija-gomologacija-2026', 'Полное руководство по гомологации медицинского диплома в Испании 2026.', content, 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&h=630&fit=crop', 'homologation', '9 min read', 'ru', 'Признание медицинской лицензии Испания 2026 | Руководство гомологация', 'Полное руководство по гомологации медицинского диплома в Испании. Процесс, документы, стоимость и сроки 2026.', 'гомологация, испания, медицинская лицензия, MEFP, Colegio de Médicos', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-license-recognition-spain-homologacion' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Medizinische Fachrichtungen in Deutschland: Facharzt-Weiterbildung Leitfaden 2026', 'medizinische-fachrichtungen-deutschland-facharzt-2026', 'Vollständiger Überblick über die Facharztweiterbildung in Deutschland.', content, 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=1200&h=630&fit=crop', 'specialties', '10 min read', 'de', 'Medizinische Fachrichtungen Deutschland 2026 | Facharzt-Weiterbildung', 'Vollständiger Leitfaden zur Facharztweiterbildung in Deutschland. Alle 34 Fachrichtungen, Dauer, Gehälter und Nachfrage.', 'Facharzt, medizinische Fachrichtungen, Weiterbildung, Deutschland', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-specialties-germany-facharzt' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Especialidades Médicas en Alemania: Guía de Formación Facharzt 2026', 'especialidades-medicas-alemania-facharzt-2026', 'Descripción completa de la formación de especialista (Facharzt) en Alemania.', content, 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=1200&h=630&fit=crop', 'specialties', '10 min read', 'es', 'Especialidades Médicas Alemania 2026 | Guía Formación Facharzt', 'Guía completa de formación Facharzt en Alemania. Las 34 especialidades, duración, salarios y demanda.', 'Facharzt, especialidades médicas, Weiterbildung, alemania', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-specialties-germany-facharzt' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Spécialités Médicales en Allemagne : Guide de Formation Facharzt 2026', 'specialites-medicales-allemagne-facharzt-2026', 'Aperçu complet de la formation de spécialiste (Facharzt) en Allemagne.', content, 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=1200&h=630&fit=crop', 'specialties', '10 min read', 'fr', 'Spécialités Médicales Allemagne 2026 | Guide Formation Facharzt', 'Guide complet de formation Facharzt en Allemagne. Les 34 spécialités, durée, salaires et demande.', 'Facharzt, spécialités médicales, Weiterbildung, allemagne', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-specialties-germany-facharzt' AND language = 'en';

INSERT INTO blog_posts (id, title, slug, excerpt, content, image_url, category, read_time, language, meta_title, meta_description, tags, author_id, status)
SELECT gen_random_uuid(), 'Медицинские специальности в Германии: Руководство по обучению Facharzt 2026', 'medicinskie-specialnosti-germanija-facharzt-2026', 'Полный обзор обучения на специалиста (Facharzt) в Германии.', content, 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=1200&h=630&fit=crop', 'specialties', '10 min read', 'ru', 'Медицинские специальности Германия 2026 | Руководство обучение Facharzt', 'Полное руководство по обучению Facharzt в Германии. Все 34 специальности, продолжительность, зарплаты и спрос.', 'Facharzt, медицинские специальности, Weiterbildung, германия', 'df03a807-9b71-4126-a409-e36ea2053f90', 'published' FROM blog_posts WHERE slug = 'medical-specialties-germany-facharzt' AND language = 'en';