
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Define constants with correct values
const SUPABASE_URL = "https://ehrxpaxvyuwiwqclqkyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVocnhwYXh2eXV3aXdxY2xxa3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDYzMjQsImV4cCI6MjA2MjEyMjMyNH0.WUheauNzi4feIFxZi9alV_6GchRC9j2hf2GAja7H5Zc";

// Log the URL being used (for debugging)
console.log("Initializing Supabase client with URL:", SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with explicit auth configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  }
});

// Add a listener to help debug auth state changes
supabase.auth.onAuthStateChange((event, session) => {
  console.log("Auth state changed:", event, session ? "User authenticated" : "No session");
});

